export const dummydata = [
  'Munchies',
  'Cold Drinks',
  'Instant',
  ' Frozen Food',
  'Tea',
  'Cofee',
  'Health Drinks',
  'Bakery ',
  'Buscuits',
  'Sweet',
  'Tooth',
  'Atta',
  'Rice',
  'Dal',
  'Dry Fruit',
  'Masala',
];

export const dummydata1 = [
  {name: 'Munchies', imgUrl: 'https://picsum.photos/200'},
  {name: 'Cold Drinks', imgUrl: 'https://picsum.photos/200'},
  {name: 'Instant', imgUrl: 'https://picsum.photos/200'},
  {name: ' Frozen Food', imgUrl: 'https://picsum.photos/200'},
  {name: 'Tea', imgUrl: 'https://picsum.photos/200'},
  {name: 'Cofee', imgUrl: 'https://picsum.photos/200'},
  {name: 'Munchies', imgUrl: 'https://picsum.photos/200'},
  {name: 'Cold Drinks', imgUrl: 'https://picsum.photos/200'},
  {name: 'Instant', imgUrl: 'https://picsum.photos/200'},
  {name: ' Frozen Food', imgUrl: 'https://picsum.photos/200'},
  {name: 'Tea', imgUrl: 'https://picsum.photos/200'},
  {name: 'Cofee', imgUrl: 'https://picsum.photos/200'},
  {name: 'Munchies', imgUrl: 'https://picsum.photos/200'},
  {name: 'Cold Drinks', imgUrl: 'https://picsum.photos/200'},
  {name: 'Instant', imgUrl: 'https://picsum.photos/200'},
  {name: ' Frozen Food', imgUrl: 'https://picsum.photos/200'},
  {name: 'Tea', imgUrl: 'https://picsum.photos/200'},
  {name: 'Cofee', imgUrl: 'https://picsum.photos/200'},
];
